FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS $DB_NAME;
CREATE USER IF NOT EXISTS $DB_USER@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWORD';
GRANT ALL ON *.* TO $DB_USER@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWORD';
FLUSH PRIVILEGES;